name: core_management_v2
description: Core management for TN mobile development
version: 0.0.1
homepage:

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=1.17.0"


dependencies:
  isar:
    version: 3.1.8
    hosted: https://pub.isar-community.dev/
  isar_flutter_libs: # contains Isar Core
      version: 3.1.8
      hosted: https://pub.isar-community.dev/

  cloud_firestore: ^5.0.1
  firebase_messaging: ^15.0.1
  flip_card: ^0.7.0
  flutter:
    sdk: flutter

  flutter_flip_card: ^0.0.4
  flutter_local_notifications: ^17.0.1
  flutter_riverpod: ^2.5.1
  fluttertoast: ^8.2.4
  go_router: ^14.0.2
  http: ^1.1.0
  image_picker: ^1.0.1
  intl: ^0.19.0
#  isar: ^3.1.0+1
  json_annotation: ^4.8.1
#  optimization_battery: ^0.0.7
  responsive_framework: ^1.0.0
  rive: ^0.13.3
  disable_battery_optimization: ^1.1.1

dev_dependencies:
  isar_generator:
    version: 3.1.8
    hosted: https://pub.isar-community.dev/
  build_runner: any
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.7.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  assets:
     - assets/rive/
#     - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
